version: '3'
# each service described here is container
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      # dot here means current working directory
      # and this is an mapping against container folder
      # and folder on our machine
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      # dot here means current working directory
      # and this is an mapping against container folder
      # and folder on our machine
      - .:/app
    command: ["npm", "run", "test"]